version: '3.8'

services:
  lab-management-system:
    build:
      context: .
      dockerfile: Dockerfile.all-in-one
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      # 持久化MySQL数据
      - mysql_data:/var/lib/mysql
      # 持久化日志
      - ./logs:/var/log/supervisor
    environment:
      - TZ=Asia/Shanghai

volumes:
  mysql_data: